#!/bin/bash -l

# Profile one paired-end sample with mOTUs 3.1.0, then write that sample in
# CAMI/bioboxes format once per requested -C mode.
#
# Reference: https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.218
#
#   motus profile -f input/ERR479298s.1.fq.gz -r input/ERR479298s.2.fq.gz \
#       -n ERR479298s -o ERR479298s-default.motus
#   motus profile -f input/ERR479298s.1.fq.gz -r input/ERR479298s.2.fq.gz \
#       -o ERR479298s-C_precision.cami -C precision
#
# The protocol reads the FASTQ files again for the CAMI call. Several modes are
# wanted here, so the reads are aligned once and the marker gene cluster counts
# are reused. -M and -m are documented flags of motus profile:
#
#   -M FILE   save the mgc reads count (output of motus calc_mgc)
#   -m FILE   provide a mgc reads count file (generated by motus calc_mgc)
#
# The mgc counts fully determine the profile, so reuse changes no number.
#
# Usage:
#   run_motus.sh read1 read2 sampleName sampleId outDir threads camiModes [motusDB]
#
#   sampleName   file stem for the outputs, e.g. sample_0
#   sampleId     the @SampleID OPAL pairs on, e.g. 0
#   camiModes    comma-separated -C modes, e.g. precision,recall,parenthesis
#   motusDB      optional path to a mOTUs database; empty means the one that
#                ships with the installed package
#
# Outputs, all in outDir:
#   <sampleName>.motus                native relative-abundance profile
#   <sampleName>.mgc.tsv              marker gene cluster read counts
#   <sampleName>.cami_<mode>.profile  one CAMI file per mode
#
set -euo pipefail

if [[ $# -lt 7 || $# -gt 8 ]]; then
    echo "usage: $0 read1 read2 sampleName sampleId outDir threads camiModes [motusDB]" >&2
    exit 1
fi

readPath1="$1"
readPath2="$2"
sampleName="$3"
sampleId="$4"
outDir="$5"
threads="$6"
camiModes="$7"
motusDB="${8:-}"

# input check
for f in "$readPath1" "$readPath2"; do
    [[ -s "$f" ]] || { echo "MISSING OR EMPTY INPUT: $f" >&2; exit 1; }
done

IFS=',' read -ra modes <<< "$camiModes"
[[ ${#modes[@]} -gt 0 ]] || { echo "NO CAMI MODES GIVEN" >&2; exit 1; }
for mode in "${modes[@]}"; do
    case "$mode" in
        precision|recall|parenthesis) ;;
        *) echo "BAD CAMI MODE: '${mode}'; use precision, recall or parenthesis" >&2; exit 1;;
    esac
done

if [[ -n "$motusDB" ]]; then
    [[ -d "$motusDB" ]] || { echo "MISSING DATABASE: $motusDB" >&2; exit 1; }
fi

command -v motus >/dev/null || { echo "motus is not on PATH" >&2; exit 1; }

mkdir -p "$outDir"

nativeOut="${outDir}/${sampleName}.motus"
mgcOut="${outDir}/${sampleName}.mgc.tsv"

# The -db flag is optional, so wrap the call instead of building an array.
run_profile() {
    if [[ -n "$motusDB" ]]; then
        motus profile -db "$motusDB" "$@"
    else
        motus profile "$@"
    fi
}

# mOTUs names the top rank "superkingdom"; the CAMI III gold standard and
# MetaScope name it "domain". OPAL groups taxa by rank name, so an unrenamed
# profile scores zero at that rank. Rename it here, so the file on disk is
# ready for OPAL and the combine step downstream is a plain cat.
rename_top_rank() {
    local f="$1"
    awk 'BEGIN { FS = OFS = "\t" }
         /^@Ranks:superkingdom/ { sub(/^@Ranks:superkingdom/, "@Ranks:domain") }
         /^[@#]/ || NF < 2 { print; next }
         $2 == "superkingdom" { $2 = "domain" }
         { print }' "$f" > "${f}.tmp"
    mv "${f}.tmp" "$f"
}

# Every CAMI profile must carry the @SampleID the gold standard uses, or OPAL
# pairs the sample with nothing and scores it as absent.
#
# mOTUs writes three '#' comment lines and a blank line before the header
# block, so the sample id is not on line 1. It also writes "@SampleID: 1" with
# a space, while the gold standard writes "@SampleID:0" without one. OPAL skips
# comments and trims the value, so both spellings pair. Compare the trimmed id.
check_cami() {
    local f="$1"
    [[ -s "$f" ]] || { echo "EMPTY OUTPUT: $f" >&2; exit 1; }
    local got
    got=$(sed -n 's/^@SampleID:[[:space:]]*//p' "$f" | head -1 | tr -d '[:space:]')
    [[ "$got" == "$sampleId" ]] \
        || { echo "WRONG @SampleID IN $f: got '${got}', want '${sampleId}'" >&2; exit 1; }
    local rows
    rows=$(awk 'NF && $0 !~ /^[@#]/' "$f" | wc -l | tr -d ' ')
    [[ "$rows" -gt 0 ]] || { echo "NO TAXON ROWS IN $f" >&2; exit 1; }
    echo "$f  ${rows} taxon rows"
}

now=$SECONDS

# profiling in mOTUs format output
echo "PROFILING ${sampleName} AS @SampleID:${sampleId}"
run_profile -f "$readPath1" -r "$readPath2" -n "$sampleId" -t "$threads" \
    -M "$mgcOut" -o "$nativeOut"
[[ -s "$nativeOut" ]] || { echo "EMPTY OUTPUT: $nativeOut" >&2; exit 1; }
[[ -s "$mgcOut" ]] || { echo "NO MARKER GENE COUNTS: $mgcOut" >&2; exit 1; }
echo "NATIVE PROFILE DONE after $((SECONDS - now))s"

# profiling in CAMI format output
for mode in "${modes[@]}"; do
    camiOut="${outDir}/${sampleName}.cami_${mode}.profile"
    run_profile -m "$mgcOut" -n "$sampleId" -C "$mode" -o "$camiOut"
    rename_top_rank "$camiOut"
    check_cami "$camiOut"
done

echo "TOTAL $((SECONDS - now))s"
